// <auto-generated />
using System;
using ExpenseProcessingSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExpenseProcessingSystem.Migrations.GOExpress
{
    [DbContext(typeof(GOExpressContext))]
    partial class GOExpressContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExpenseProcessingSystem.Models.Gbase.tblCM10Model", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AUTO_APPROVED");

                    b.Property<string>("BRANCHNO");

                    b.Property<string>("CCY_FORMAT");

                    b.Property<string>("COMMENT");

                    b.Property<DateTime>("DATESTAMP");

                    b.Property<string>("EMPNO");

                    b.Property<string>("ENTRY11_ACTCDE");

                    b.Property<string>("ENTRY11_ACT_NO");

                    b.Property<string>("ENTRY11_ACT_TYPE");

                    b.Property<string>("ENTRY11_ADVC_PRNT");

                    b.Property<string>("ENTRY11_AMT");

                    b.Property<string>("ENTRY11_AVAILABLE");

                    b.Property<string>("ENTRY11_CCY");

                    b.Property<string>("ENTRY11_CHECK_NO");

                    b.Property<string>("ENTRY11_CUST");

                    b.Property<string>("ENTRY11_DETAILS");

                    b.Property<string>("ENTRY11_DIVISION");

                    b.Property<string>("ENTRY11_EXCH_CCY");

                    b.Property<string>("ENTRY11_EXCH_RATE");

                    b.Property<string>("ENTRY11_FUND");

                    b.Property<string>("ENTRY11_IBF_CODE");

                    b.Property<string>("ENTRY11_INTER_AMT");

                    b.Property<string>("ENTRY11_INTER_RATE");

                    b.Property<string>("ENTRY11_TYPE");

                    b.Property<string>("ENTRY22_ACTCDE");

                    b.Property<string>("ENTRY22_ACT_NO");

                    b.Property<string>("ENTRY22_ACT_TYPE");

                    b.Property<string>("ENTRY22_ADVC_PRNT");

                    b.Property<string>("ENTRY22_AMT");

                    b.Property<string>("ENTRY22_AVAILABLE");

                    b.Property<string>("ENTRY22_CCY");

                    b.Property<string>("ENTRY22_CHECK_NO");

                    b.Property<string>("ENTRY22_CUST");

                    b.Property<string>("ENTRY22_DETAILS");

                    b.Property<string>("ENTRY22_DIVISION");

                    b.Property<string>("ENTRY22_EXCH_CCY");

                    b.Property<string>("ENTRY22_EXCH_RATE");

                    b.Property<string>("ENTRY22_FUND");

                    b.Property<string>("ENTRY22_IBF_CODE");

                    b.Property<string>("ENTRY22_INTER_AMT");

                    b.Property<string>("ENTRY22_INTER_RATE");

                    b.Property<string>("ENTRY22_TYPE");

                    b.Property<string>("ENTRY33_ACTCDE");

                    b.Property<string>("ENTRY33_ACT_NO");

                    b.Property<string>("ENTRY33_ACT_TYPE");

                    b.Property<string>("ENTRY33_ADVC_PRNT");

                    b.Property<string>("ENTRY33_AMT");

                    b.Property<string>("ENTRY33_AVAILABLE");

                    b.Property<string>("ENTRY33_CCY");

                    b.Property<string>("ENTRY33_CHECK_NO");

                    b.Property<string>("ENTRY33_CUST");

                    b.Property<string>("ENTRY33_DETAILS");

                    b.Property<string>("ENTRY33_DIVISION");

                    b.Property<string>("ENTRY33_EXCH_CCY");

                    b.Property<string>("ENTRY33_EXCH_RATE");

                    b.Property<string>("ENTRY33_FUND");

                    b.Property<string>("ENTRY33_IBF_CODE");

                    b.Property<string>("ENTRY33_INTER_AMT");

                    b.Property<string>("ENTRY33_INTER_RATE");

                    b.Property<string>("ENTRY33_TYPE");

                    b.Property<string>("ENTRY44_ACTCDE");

                    b.Property<string>("ENTRY44_ACT_NO");

                    b.Property<string>("ENTRY44_ACT_TYPE");

                    b.Property<string>("ENTRY44_ADVC_PRNT");

                    b.Property<string>("ENTRY44_AMT");

                    b.Property<string>("ENTRY44_AVAILABLE");

                    b.Property<string>("ENTRY44_CCY");

                    b.Property<string>("ENTRY44_CHECK_NO");

                    b.Property<string>("ENTRY44_CUST");

                    b.Property<string>("ENTRY44_DETAILS");

                    b.Property<string>("ENTRY44_DIVISION");

                    b.Property<string>("ENTRY44_EXCH_CCY");

                    b.Property<string>("ENTRY44_EXCH_RATE");

                    b.Property<string>("ENTRY44_FUND");

                    b.Property<string>("ENTRY44_IBF_CODE");

                    b.Property<string>("ENTRY44_INTER_AMT");

                    b.Property<string>("ENTRY44_INTER_RATE");

                    b.Property<string>("ENTRY44_TYPE");

                    b.Property<string>("GROUPCODE");

                    b.Property<string>("MAKER_EMPNO");

                    b.Property<string>("MEMO");

                    b.Property<string>("OPE_BRANCH");

                    b.Property<string>("OPE_KIND");

                    b.Property<string>("RECSTATUS");

                    b.Property<string>("REFERENCE_NO");

                    b.Property<string>("REFERENCE_TYPE");

                    b.Property<string>("REMARKS");

                    b.Property<string>("SCHEME_NO");

                    b.Property<string>("SECTION");

                    b.Property<string>("SYSTEM_NAME");

                    b.Property<DateTime>("TIMERESPOND");

                    b.Property<DateTime>("TIMESENT");

                    b.Property<string>("TRANSNO");

                    b.Property<string>("VALUE_DATE");

                    b.Property<string>("WARNING_OVERRIDE");

                    b.Property<string>("XMLMSG");

                    b.HasKey("ID");

                    b.ToTable("tblCM10");
                });
#pragma warning restore 612, 618
        }
    }
}
