using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExpenseProcessingSystem.ViewModels
{
    public class HomeReportTransactionListViewModel
    {
        //Needed in report
        public string Trans_Voucher_Number { get; set; }
        public string Trans_Check_Number { get; set; }
        public string Trans_Value_Date { get; set; }
        public string Trans_Reference_No { get; set; }
        public string Trans_Section { get; set; }
        public string Trans_Remarks { get; set; }
        public string Trans_DebitCredit1_1 { get; set; }
        public string Trans_Currency1_1 { get; set; }
        public string Trans_Amount1_1 { get; set; }
        public string Trans_Customer1_1 { get; set; }
        public string Trans_Account_Code1_1 { get; set; }
        public string Trans_Account_Number1_1 { get; set; }
        public string Trans_Account_Name1_1 { get; set; }
        public string Trans_Exchange_Rate1_1 { get; set; }
        public string Trans_Contra_Currency1_1 { get; set; }
        public string Trans_Fund1_1 { get; set; }
        public string Trans_Advice_Print1_1 { get; set; }
        public string Trans_Details1_1 { get; set; }
        public string Trans_Entity1_1 { get; set; }
        public string Trans_Division1_1 { get; set; }
        public string Trans_InterAmount1_1 { get; set; }
        public string Trans_InterRate1_1 { get; set; }
        public string Trans_DebitCredit1_2 { get; set; }
        public string Trans_Currency1_2 { get; set; }
        public string Trans_Amount1_2 { get; set; }
        public string Trans_Customer1_2 { get; set; }
        public string Trans_Account_Code1_2 { get; set; }
        public string Trans_Account_Number1_2 { get; set; }
        public string Trans_Account_Name1_2 { get; set; }
        public string Trans_Exchange_Rate1_2 { get; set; }
        public string Trans_Contra_Currency1_2 { get; set; }
        public string Trans_Fund1_2 { get; set; }
        public string Trans_Advice_Print1_2 { get; set; }
        public string Trans_Details1_2 { get; set; }
        public string Trans_Entity1_2 { get; set; }
        public string Trans_Division1_2 { get; set; }
        public string Trans_InterAmount1_2 { get; set; }
        public string Trans_InterRate1_2 { get; set; }
        public string Trans_DebitCredit2_1 { get; set; }
        public string Trans_Currency2_1 { get; set; }
        public string Trans_Amount2_1 { get; set; }
        public string Trans_Customer2_1 { get; set; }
        public string Trans_Account_Code2_1 { get; set; }
        public string Trans_Account_Number2_1 { get; set; }
        public string Trans_Account_Name2_1 { get; set; }
        public string Trans_Exchange_Rate2_1 { get; set; }
        public string Trans_Contra_Currency2_1 { get; set; }
        public string Trans_Fund2_1 { get; set; }
        public string Trans_Advice_Print2_1 { get; set; }
        public string Trans_Details2_1 { get; set; }
        public string Trans_Entity2_1 { get; set; }
        public string Trans_Division2_1 { get; set; }
        public string Trans_InterAmount2_1 { get; set; }
        public string Trans_InterRate2_1 { get; set; }
        public string Trans_DebitCredit2_2 { get; set; }
        public string Trans_Currency2_2 { get; set; }
        public string Trans_Amount2_2 { get; set; }
        public string Trans_Customer2_2 { get; set; }
        public string Trans_Account_Code2_2 { get; set; }
        public string Trans_Account_Number2_2 { get; set; }
        public string Trans_Account_Name2_2 { get; set; }
        public string Trans_Exchange_Rate2_2 { get; set; }
        public string Trans_Contra_Currency2_2 { get; set; }
        public string Trans_Fund2_2 { get; set; }
        public string Trans_Advice_Print2_2 { get; set; }
        public string Trans_Details2_2 { get; set; }
        public string Trans_Entity2_2 { get; set; }
        public string Trans_Division2_2 { get; set; }
        public string Trans_InterAmount2_2 { get; set; }
        public string Trans_InterRate2_2 { get; set; }
        public string Trans_DebitCredit3_1 { get; set; }
        public string Trans_Currency3_1 { get; set; }
        public string Trans_Amount3_1 { get; set; }
        public string Trans_Customer3_1 { get; set; }
        public string Trans_Account_Code3_1 { get; set; }
        public string Trans_Account_Number3_1 { get; set; }
        public string Trans_Account_Name3_1 { get; set; }
        public string Trans_Exchange_Rate3_1 { get; set; }
        public string Trans_Contra_Currency3_1 { get; set; }
        public string Trans_Fund3_1 { get; set; }
        public string Trans_Advice_Print3_1 { get; set; }
        public string Trans_Details3_1 { get; set; }
        public string Trans_Entity3_1 { get; set; }
        public string Trans_Division3_1 { get; set; }
        public string Trans_InterAmount3_1 { get; set; }
        public string Trans_InterRate3_1 { get; set; }
        public string Trans_DebitCredit3_2 { get; set; }
        public string Trans_Currency3_2 { get; set; }
        public string Trans_Amount3_2 { get; set; }
        public string Trans_Customer3_2 { get; set; }
        public string Trans_Account_Code3_2 { get; set; }
        public string Trans_Account_Number3_2 { get; set; }
        public string Trans_Account_Name3_2 { get; set; }
        public string Trans_Exchange_Rate3_2 { get; set; }
        public string Trans_Contra_Currency3_2 { get; set; }
        public string Trans_Fund3_2 { get; set; }
        public string Trans_Advice_Print3_2 { get; set; }
        public string Trans_Details3_2 { get; set; }
        public string Trans_Entity3_2 { get; set; }
        public string Trans_Division3_2 { get; set; }
        public string Trans_InterAmount3_2 { get; set; }
        public string Trans_InterRate3_2 { get; set; }
        public string Trans_DebitCredit4_1 { get; set; }
        public string Trans_Currency4_1 { get; set; }
        public string Trans_Amount4_1 { get; set; }
        public string Trans_Customer4_1 { get; set; }
        public string Trans_Account_Code4_1 { get; set; }
        public string Trans_Account_Number4_1 { get; set; }
        public string Trans_Account_Name4_1 { get; set; }
        public string Trans_Exchange_Rate4_1 { get; set; }
        public string Trans_Contra_Currency4_1 { get; set; }
        public string Trans_Fund4_1 { get; set; }
        public string Trans_Advice_Print4_1 { get; set; }
        public string Trans_Details4_1 { get; set; }
        public string Trans_Entity4_1 { get; set; }
        public string Trans_Division4_1 { get; set; }
        public string Trans_InterAmount4_1 { get; set; }
        public string Trans_InterRate4_1 { get; set; }
        public string Trans_DebitCredit4_2 { get; set; }
        public string Trans_Currency4_2 { get; set; }
        public string Trans_Amount4_2 { get; set; }
        public string Trans_Customer4_2 { get; set; }
        public string Trans_Account_Code4_2 { get; set; }
        public string Trans_Account_Number4_2 { get; set; }
        public string Trans_Account_Name4_2 { get; set; }
        public string Trans_Exchange_Rate4_2 { get; set; }
        public string Trans_Contra_Currency4_2 { get; set; }
        public string Trans_Fund4_2 { get; set; }
        public string Trans_Advice_Print4_2 { get; set; }
        public string Trans_Details4_2 { get; set; }
        public string Trans_Entity4_2 { get; set; }
        public string Trans_Division4_2 { get; set; }
        public string Trans_InterAmount4_2 { get; set; }
        public string Trans_InterRate4_2 { get; set; }

        //Etc
        public int ExpExpense_ID { get; set; }
        public int ExpExpense_Type { get; set; }
        public string ExpExpense_Date { get; set; }
        public int HistExpenseEntryID { get; set; }
        public int HistExpenseDetailID { get; set; }
        public int HistGOExpHist_Id { get; set; }
        public string HistGOExpHist_ValueDate { get; set; }
        public string HistGOExpHist_ReferenceNo { get; set; }
        public string HistGOExpHist_Section { get; set; }
        public string HistGOExpHist_Remarks { get; set; }
        public string HistGOExpHist_Memo { get; set; }
        public int TransTL_ID { get; set; }
        public int TransTL_GoExpress_ID { get; set; }
        public int TransTL_TransID { get; set; }
        public int NCExpNC_Category_ID { get; set; }
        public DateTime Trans_Last_Updated_Date { get; set; }

        //For ESAMS Report
        public string ESAMS_SeqNo { get; set; }
        public string ESAMS_MakerName { get; set; }
        public string ESAMS_ApprvName { get; set; }
    }
}
