// <auto-generated />
using System;
using ExpenseProcessingSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExpenseProcessingSystem.Migrations
{
    [DbContext(typeof(EPSDbContext))]
    [Migration("20190709090254_DDVAddEWTPayorId")]
    partial class DDVAddEWTPayorId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExpenseProcessingSystem.Models.BudgetModel", b =>
                {
                    b.Property<int>("Budget_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Budget_Account_ID");

                    b.Property<int>("Budget_Account_MasterID");

                    b.Property<double>("Budget_Amount");

                    b.Property<int>("Budget_Creator_ID");

                    b.Property<DateTime>("Budget_Date_Registered");

                    b.Property<bool>("Budget_IsActive");

                    b.Property<bool>("Budget_isDeleted");

                    b.HasKey("Budget_ID");

                    b.ToTable("Budget");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.ClosingModel", b =>
                {
                    b.Property<int>("Close_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Close_Date");

                    b.Property<DateTime>("Close_Open_Date");

                    b.Property<int>("Close_Status");

                    b.Property<int>("Close_User");

                    b.HasKey("Close_ID");

                    b.ToTable("Closing");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.DMAccountGroupModel", b =>
                {
                    b.Property<int>("AccountGroup_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountGroup_Approver_ID");

                    b.Property<string>("AccountGroup_Code");

                    b.Property<DateTime>("AccountGroup_Created_Date");

                    b.Property<int>("AccountGroup_Creator_ID");

                    b.Property<DateTime>("AccountGroup_Last_Updated");

                    b.Property<int>("AccountGroup_MasterID");

                    b.Property<string>("AccountGroup_Name");

                    b.Property<int>("AccountGroup_Status_ID");

                    b.Property<bool>("AccountGroup_isActive");

                    b.Property<bool>("AccountGroup_isDeleted");

                    b.HasKey("AccountGroup_ID");

                    b.ToTable("DMAccountGroup");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.DMAccountModel", b =>
                {
                    b.Property<int>("Account_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Account_Approver_ID");

                    b.Property<string>("Account_Budget_Code");

                    b.Property<string>("Account_Code");

                    b.Property<DateTime>("Account_Created_Date");

                    b.Property<int>("Account_Creator_ID");

                    b.Property<int>("Account_Currency_MasterID");

                    b.Property<string>("Account_Cust");

                    b.Property<string>("Account_Div");

                    b.Property<int>("Account_FBT_MasterID");

                    b.Property<bool>("Account_Fund");

                    b.Property<int>("Account_Group_MasterID");

                    b.Property<DateTime>("Account_Last_Updated");

                    b.Property<int>("Account_MasterID");

                    b.Property<string>("Account_Name");

                    b.Property<string>("Account_No");

                    b.Property<int>("Account_Status_ID");

                    b.Property<bool>("Account_isActive");

                    b.Property<bool>("Account_isDeleted");

                    b.HasKey("Account_ID");

                    b.ToTable("DMAccount");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.DMAccountModel_Pending", b =>
                {
                    b.Property<int>("Pending_Account_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Pending_Account_Approver_ID");

                    b.Property<string>("Pending_Account_Budget_Code");

                    b.Property<string>("Pending_Account_Code");

                    b.Property<int>("Pending_Account_Creator_ID");

                    b.Property<int>("Pending_Account_Currency_MasterID");

                    b.Property<string>("Pending_Account_Cust");

                    b.Property<string>("Pending_Account_Div");

                    b.Property<int>("Pending_Account_FBT_MasterID");

                    b.Property<DateTime>("Pending_Account_Filed_Date");

                    b.Property<bool>("Pending_Account_Fund");

                    b.Property<int>("Pending_Account_Group_MasterID");

                    b.Property<int>("Pending_Account_MasterID");

                    b.Property<string>("Pending_Account_Name");

                    b.Property<string>("Pending_Account_No");

                    b.Property<int>("Pending_Account_Status_ID");

                    b.Property<bool>("Pending_Account_isActive");

                    b.Property<bool>("Pending_Account_isDeleted");

                    b.HasKey("Pending_Account_ID");

                    b.ToTable("DMAccount_Pending");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.DMBIRCertSignModel", b =>
                {
                    b.Property<int>("BCS_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BCS_Approver_ID");

                    b.Property<DateTime>("BCS_Created_Date");

                    b.Property<int>("BCS_Creator_ID");

                    b.Property<DateTime>("BCS_Last_Updated");

                    b.Property<int>("BCS_MasterID");

                    b.Property<string>("BCS_Name");

                    b.Property<string>("BCS_Position");

                    b.Property<string>("BCS_Signatures");

                    b.Property<int>("BCS_Status_ID");

                    b.Property<string>("BCS_TIN");

                    b.Property<bool>("BCS_isActive");

                    b.Property<bool>("BCS_isDeleted");

                    b.HasKey("BCS_ID");

                    b.ToTable("DMBCS");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.DMCheckModel", b =>
                {
                    b.Property<int>("Check_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Check_Approver_ID");

                    b.Property<string>("Check_Bank_Info");

                    b.Property<DateTime>("Check_Created_Date");

                    b.Property<int>("Check_Creator_ID");

                    b.Property<DateTime>("Check_Input_Date");

                    b.Property<DateTime>("Check_Last_Updated");

                    b.Property<int>("Check_MasterID");

                    b.Property<string>("Check_Series_From");

                    b.Property<string>("Check_Series_To");

                    b.Property<int>("Check_Status_ID");

                    b.Property<bool>("Check_isActive");

                    b.Property<bool>("Check_isDeleted");

                    b.HasKey("Check_ID");

                    b.ToTable("DMCheck");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.DMCheckModel_Pending", b =>
                {
                    b.Property<int>("Pending_Check_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Pending_Check_Approver_ID");

                    b.Property<string>("Pending_Check_Bank_Info");

                    b.Property<int>("Pending_Check_Creator_ID");

                    b.Property<DateTime>("Pending_Check_Filed_Date");

                    b.Property<DateTime>("Pending_Check_Input_Date");

                    b.Property<int>("Pending_Check_MasterID");

                    b.Property<string>("Pending_Check_Series_From");

                    b.Property<string>("Pending_Check_Series_To");

                    b.Property<int>("Pending_Check_Status_ID");

                    b.Property<bool>("Pending_Check_isActive");

                    b.Property<bool>("Pending_Check_isDeleted");

                    b.HasKey("Pending_Check_ID");

                    b.ToTable("DMCheck_Pending");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.DMCurrencyModel", b =>
                {
                    b.Property<int>("Curr_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Curr_Approver_ID");

                    b.Property<string>("Curr_CCY_ABBR");

                    b.Property<DateTime>("Curr_Created_Date");

                    b.Property<int>("Curr_Creator_ID");

                    b.Property<DateTime>("Curr_Last_Updated");

                    b.Property<int>("Curr_MasterID");

                    b.Property<string>("Curr_Name");

                    b.Property<int>("Curr_Status_ID");

                    b.Property<bool>("Curr_isActive");

                    b.Property<bool>("Curr_isDeleted");

                    b.HasKey("Curr_ID");

                    b.ToTable("DMCurrency");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.DMCustModel", b =>
                {
                    b.Property<int>("Cust_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cust_Abbr");

                    b.Property<int>("Cust_Approver_ID");

                    b.Property<DateTime>("Cust_Created_Date");

                    b.Property<int>("Cust_Creator_ID");

                    b.Property<DateTime>("Cust_Last_Updated");

                    b.Property<int>("Cust_MasterID");

                    b.Property<string>("Cust_Name");

                    b.Property<string>("Cust_No");

                    b.Property<int>("Cust_Status_ID");

                    b.Property<bool>("Cust_isActive");

                    b.Property<bool>("Cust_isDeleted");

                    b.HasKey("Cust_ID");

                    b.ToTable("DMCust");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.DMDeptModel", b =>
                {
                    b.Property<int>("Dept_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Dept_Approver_ID");

                    b.Property<string>("Dept_Budget_Unit");

                    b.Property<string>("Dept_Code");

                    b.Property<DateTime>("Dept_Created_Date");

                    b.Property<int>("Dept_Creator_ID");

                    b.Property<DateTime>("Dept_Last_Updated");

                    b.Property<int>("Dept_MasterID");

                    b.Property<string>("Dept_Name");

                    b.Property<int>("Dept_Status_ID");

                    b.Property<bool>("Dept_isActive");

                    b.Property<bool>("Dept_isDeleted");

                    b.HasKey("Dept_ID");

                    b.ToTable("DMDept");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.DMDeptModel_Pending", b =>
                {
                    b.Property<int>("Pending_Dept_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Pending_Dept_Approver_ID");

                    b.Property<string>("Pending_Dept_Budget_Unit");

                    b.Property<string>("Pending_Dept_Code");

                    b.Property<int>("Pending_Dept_Creator_ID");

                    b.Property<DateTime>("Pending_Dept_Filed_Date");

                    b.Property<int>("Pending_Dept_MasterID");

                    b.Property<string>("Pending_Dept_Name");

                    b.Property<int>("Pending_Dept_Status_ID");

                    b.Property<bool>("Pending_Dept_isActive");

                    b.Property<bool>("Pending_Dept_isDeleted");

                    b.HasKey("Pending_Dept_ID");

                    b.ToTable("DMDept_Pending");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.DMEmpModel", b =>
                {
                    b.Property<int>("Emp_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Emp_Acc_No");

                    b.Property<int>("Emp_Approver_ID");

                    b.Property<DateTime>("Emp_Created_Date");

                    b.Property<int>("Emp_Creator_ID");

                    b.Property<DateTime>("Emp_Last_Updated");

                    b.Property<int>("Emp_MasterID");

                    b.Property<string>("Emp_Name");

                    b.Property<int>("Emp_Status_ID");

                    b.Property<string>("Emp_Type");

                    b.Property<bool>("Emp_isActive");

                    b.Property<bool>("Emp_isDeleted");

                    b.HasKey("Emp_ID");

                    b.ToTable("DMEmp");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.DMFBTModel", b =>
                {
                    b.Property<int>("FBT_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FBT_Abbr");

                    b.Property<int>("FBT_Approver_ID");

                    b.Property<DateTime>("FBT_Created_Date");

                    b.Property<int>("FBT_Creator_ID");

                    b.Property<string>("FBT_Formula");

                    b.Property<DateTime>("FBT_Last_Updated");

                    b.Property<int>("FBT_MasterID");

                    b.Property<string>("FBT_Name");

                    b.Property<int>("FBT_Status_ID");

                    b.Property<float>("FBT_Tax_Rate");

                    b.Property<bool>("FBT_isActive");

                    b.Property<bool>("FBT_isDeleted");

                    b.HasKey("FBT_ID");

                    b.ToTable("DMFBT");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.DMTRModel", b =>
                {
                    b.Property<int>("TR_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TR_ATC");

                    b.Property<int>("TR_Approver_ID");

                    b.Property<DateTime>("TR_Created_Date");

                    b.Property<int>("TR_Creator_ID");

                    b.Property<DateTime>("TR_Last_Updated");

                    b.Property<int>("TR_MasterID");

                    b.Property<string>("TR_Nature");

                    b.Property<string>("TR_Nature_Income_Payment");

                    b.Property<int>("TR_Status_ID");

                    b.Property<float>("TR_Tax_Rate");

                    b.Property<string>("TR_WT_Title");

                    b.Property<bool>("TR_isActive");

                    b.Property<bool>("TR_isDeleted");

                    b.HasKey("TR_ID");

                    b.ToTable("DMTR");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.DMVATModel", b =>
                {
                    b.Property<int>("VAT_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("VAT_Approver_ID");

                    b.Property<DateTime>("VAT_Created_Date");

                    b.Property<int>("VAT_Creator_ID");

                    b.Property<DateTime>("VAT_Last_Updated");

                    b.Property<int>("VAT_MasterID");

                    b.Property<string>("VAT_Name");

                    b.Property<float>("VAT_Rate");

                    b.Property<int>("VAT_Status_ID");

                    b.Property<bool>("VAT_isActive");

                    b.Property<bool>("VAT_isDeleted");

                    b.HasKey("VAT_ID");

                    b.ToTable("DMVAT");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.DMVendorModel", b =>
                {
                    b.Property<int>("Vendor_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Vendor_Address");

                    b.Property<int>("Vendor_Approver_ID");

                    b.Property<DateTime>("Vendor_Created_Date");

                    b.Property<int>("Vendor_Creator_ID");

                    b.Property<DateTime>("Vendor_Last_Updated");

                    b.Property<int>("Vendor_MasterID");

                    b.Property<string>("Vendor_Name");

                    b.Property<int>("Vendor_Status_ID");

                    b.Property<string>("Vendor_TIN");

                    b.Property<int>("Vendor_Zip");

                    b.Property<bool>("Vendor_isActive");

                    b.Property<bool>("Vendor_isDeleted");

                    b.HasKey("Vendor_ID");

                    b.ToTable("DMVendor");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.DMVendorModel_Pending", b =>
                {
                    b.Property<int>("Pending_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Pending_Vendor_Address");

                    b.Property<int>("Pending_Vendor_Approver_ID");

                    b.Property<int>("Pending_Vendor_Creator_ID");

                    b.Property<DateTime>("Pending_Vendor_Filed_Date");

                    b.Property<bool>("Pending_Vendor_IsDeleted");

                    b.Property<int>("Pending_Vendor_MasterID");

                    b.Property<string>("Pending_Vendor_Name");

                    b.Property<int>("Pending_Vendor_Status_ID");

                    b.Property<string>("Pending_Vendor_TIN");

                    b.Property<bool>("Pending_Vendor_isActive");

                    b.HasKey("Pending_ID");

                    b.ToTable("DMVendor_Pending");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.DMVendorTRVATModel", b =>
                {
                    b.Property<int>("VTV_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("VTV_TR_ID");

                    b.Property<int>("VTV_VAT_ID");

                    b.Property<int>("VTV_Vendor_ID");

                    b.HasKey("VTV_ID");

                    b.ToTable("DMVendorTRVAT");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.ExpenseEntryAmortizationModel", b =>
                {
                    b.Property<int>("Amor_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Amor_Number");

                    b.Property<float>("Amor_Price");

                    b.Property<DateTime>("Amor_Sched_Date");

                    b.Property<string>("Amor_Status");

                    b.Property<int?>("ExpenseEntryDetailModelExpDtl_ID");

                    b.HasKey("Amor_ID");

                    b.HasIndex("ExpenseEntryDetailModelExpDtl_ID");

                    b.ToTable("ExpenseEntryAmortizations");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.ExpenseEntryCashBreakdownModel", b =>
                {
                    b.Property<int>("CashBreak_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CashBreak_Amount");

                    b.Property<double>("CashBreak_Denomination");

                    b.Property<int>("CashBreak_NoPcs");

                    b.Property<int?>("ExpenseEntryDetailModelExpDtl_ID");

                    b.HasKey("CashBreak_ID");

                    b.HasIndex("ExpenseEntryDetailModelExpDtl_ID");

                    b.ToTable("ExpenseEntryCashBreakdown");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.ExpenseEntryDetailModel", b =>
                {
                    b.Property<int>("ExpDtl_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExpDtl_Account");

                    b.Property<int>("ExpDtl_Amor_Day");

                    b.Property<int>("ExpDtl_Amor_Duration");

                    b.Property<int>("ExpDtl_Amor_Month");

                    b.Property<int>("ExpDtl_Ccy");

                    b.Property<float>("ExpDtl_Credit_Cash");

                    b.Property<float>("ExpDtl_Credit_Ewt");

                    b.Property<float>("ExpDtl_Debit");

                    b.Property<int>("ExpDtl_Dept");

                    b.Property<int>("ExpDtl_Ewt");

                    b.Property<int>("ExpDtl_Ewt_Payor_Name_ID");

                    b.Property<bool>("ExpDtl_Fbt");

                    b.Property<int>("ExpDtl_FbtID");

                    b.Property<string>("ExpDtl_Gbase_Remarks");

                    b.Property<bool>("ExpDtl_Inter_Entity");

                    b.Property<int>("ExpDtl_SS_Payee");

                    b.Property<int>("ExpDtl_Vat");

                    b.Property<bool>("ExpDtl_isEwt");

                    b.Property<int?>("ExpenseEntryModelExpense_ID");

                    b.HasKey("ExpDtl_ID");

                    b.HasIndex("ExpenseEntryModelExpense_ID");

                    b.ToTable("ExpenseEntryDetails");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.ExpenseEntryGbaseDtl", b =>
                {
                    b.Property<int>("GbaseDtl_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ExpenseEntryDetailModelExpDtl_ID");

                    b.Property<float>("GbaseDtl_Amount");

                    b.Property<string>("GbaseDtl_Description");

                    b.Property<string>("GbaseDtl_Document_Type");

                    b.Property<string>("GbaseDtl_InvoiceNo");

                    b.HasKey("GbaseDtl_ID");

                    b.HasIndex("ExpenseEntryDetailModelExpDtl_ID");

                    b.ToTable("ExpenseEntryGbaseDtls");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.ExpenseEntryInterEntityAccsModel", b =>
                {
                    b.Property<int>("InterAcc_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ExpenseEntryInterEntityParticularInterPart_ID");

                    b.Property<int>("InterAcc_Acc_ID");

                    b.Property<float>("InterAcc_Amount");

                    b.Property<int>("InterAcc_Curr_ID");

                    b.Property<float>("InterAcc_Rate");

                    b.Property<int>("InterAcc_Type_ID");

                    b.HasKey("InterAcc_ID");

                    b.HasIndex("ExpenseEntryInterEntityParticularInterPart_ID");

                    b.ToTable("ExpenseEntryInterEntityAccs");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.ExpenseEntryInterEntityModel", b =>
                {
                    b.Property<int>("ExpDtl_DDVInter_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("ExpDtl_DDVInter_Amount1");

                    b.Property<float>("ExpDtl_DDVInter_Amount2");

                    b.Property<bool>("ExpDtl_DDVInter_Check1");

                    b.Property<bool>("ExpDtl_DDVInter_Check2");

                    b.Property<float>("ExpDtl_DDVInter_Conv_Amount1");

                    b.Property<float>("ExpDtl_DDVInter_Conv_Amount2");

                    b.Property<int>("ExpDtl_DDVInter_Curr1_ID");

                    b.Property<int>("ExpDtl_DDVInter_Curr2_ID");

                    b.Property<float>("ExpDtl_DDVInter_Rate");

                    b.Property<int?>("ExpenseEntryDetailModelExpDtl_ID");

                    b.HasKey("ExpDtl_DDVInter_ID");

                    b.HasIndex("ExpenseEntryDetailModelExpDtl_ID");

                    b.ToTable("ExpenseEntryInterEntity");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.ExpenseEntryInterEntityParticularModel", b =>
                {
                    b.Property<int>("InterPart_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ExpenseEntryInterEntityModelExpDtl_DDVInter_ID");

                    b.Property<string>("InterPart_Particular_Title");

                    b.HasKey("InterPart_ID");

                    b.HasIndex("ExpenseEntryInterEntityModelExpDtl_DDVInter_ID");

                    b.ToTable("ExpenseEntryInterEntityParticular");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.ExpenseEntryModel", b =>
                {
                    b.Property<int>("Expense_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Expense_Approver");

                    b.Property<int>("Expense_CheckId");

                    b.Property<string>("Expense_CheckNo");

                    b.Property<DateTime>("Expense_Created_Date");

                    b.Property<int>("Expense_Creator_ID");

                    b.Property<float>("Expense_Credit_Total");

                    b.Property<DateTime>("Expense_Date");

                    b.Property<float>("Expense_Debit_Total");

                    b.Property<DateTime>("Expense_Last_Updated");

                    b.Property<int>("Expense_Number");

                    b.Property<int>("Expense_Payee");

                    b.Property<int>("Expense_Status");

                    b.Property<int>("Expense_Type");

                    b.Property<int>("Expense_Verifier_1");

                    b.Property<int>("Expense_Verifier_2");

                    b.Property<bool>("Expense_isDeleted");

                    b.HasKey("Expense_ID");

                    b.ToTable("ExpenseEntry");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.ExpenseEntryNCDtlAccModel", b =>
                {
                    b.Property<int>("ExpNCDtlAcc_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExpNCDtlAcc_Acc_ID");

                    b.Property<string>("ExpNCDtlAcc_Acc_Name");

                    b.Property<float>("ExpNCDtlAcc_Amount");

                    b.Property<int>("ExpNCDtlAcc_Curr_ID");

                    b.Property<float>("ExpNCDtlAcc_Inter_Rate");

                    b.Property<int>("ExpNCDtlAcc_Type_ID");

                    b.Property<int?>("ExpenseEntryNCDtlModelExpNCDtl_ID");

                    b.HasKey("ExpNCDtlAcc_ID");

                    b.HasIndex("ExpenseEntryNCDtlModelExpNCDtl_ID");

                    b.ToTable("ExpenseEntryNonCashDetailAccounts");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.ExpenseEntryNCDtlModel", b =>
                {
                    b.Property<int>("ExpNCDtl_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExpNCDtl_Remarks_Desc");

                    b.Property<string>("ExpNCDtl_Remarks_Period");

                    b.Property<int?>("ExpenseEntryNCModelExpNC_ID");

                    b.HasKey("ExpNCDtl_ID");

                    b.HasIndex("ExpenseEntryNCModelExpNC_ID");

                    b.ToTable("ExpenseEntryNonCashDetails");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.ExpenseEntryNCModel", b =>
                {
                    b.Property<int>("ExpNC_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("ExpNC_CS_CredAmt");

                    b.Property<float>("ExpNC_CS_DebitAmt");

                    b.Property<int>("ExpNC_Category_ID");

                    b.Property<float>("ExpNC_CredAmt");

                    b.Property<float>("ExpNC_DebitAmt");

                    b.Property<float>("ExpNC_IE_CredAmt");

                    b.Property<float>("ExpNC_IE_DebitAmt");

                    b.Property<int?>("ExpenseEntryModelExpense_ID");

                    b.HasKey("ExpNC_ID");

                    b.HasIndex("ExpenseEntryModelExpense_ID");

                    b.ToTable("ExpenseEntryNonCash");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.ExpenseTransList", b =>
                {
                    b.Property<int>("TL_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TL_ExpenseID");

                    b.Property<int>("TL_GoExpress_ID");

                    b.Property<bool>("TL_Liquidation");

                    b.Property<int>("TL_TransID");

                    b.HasKey("TL_ID");

                    b.ToTable("ExpenseTransLists");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.FileLocationModel", b =>
                {
                    b.Property<int>("FL_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FL_Location");

                    b.Property<string>("FL_Type");

                    b.HasKey("FL_ID");

                    b.ToTable("FileLocation");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.GOExpressHistModel", b =>
                {
                    b.Property<int>("GOExpHist_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ExpenseEntryModelExpense_ID");

                    b.Property<string>("GOExpHist_AutoApproved");

                    b.Property<string>("GOExpHist_Branchno");

                    b.Property<string>("GOExpHist_CcyFormat");

                    b.Property<string>("GOExpHist_Comment");

                    b.Property<string>("GOExpHist_Entry11ActNo");

                    b.Property<string>("GOExpHist_Entry11ActType");

                    b.Property<string>("GOExpHist_Entry11Actcde");

                    b.Property<string>("GOExpHist_Entry11AdvcPrnt");

                    b.Property<string>("GOExpHist_Entry11Amt");

                    b.Property<string>("GOExpHist_Entry11Available");

                    b.Property<string>("GOExpHist_Entry11Ccy");

                    b.Property<string>("GOExpHist_Entry11CheckNo");

                    b.Property<string>("GOExpHist_Entry11Cust");

                    b.Property<string>("GOExpHist_Entry11Details");

                    b.Property<string>("GOExpHist_Entry11Division");

                    b.Property<string>("GOExpHist_Entry11Entity");

                    b.Property<string>("GOExpHist_Entry11ExchCcy");

                    b.Property<string>("GOExpHist_Entry11ExchRate");

                    b.Property<string>("GOExpHist_Entry11Fund");

                    b.Property<string>("GOExpHist_Entry11IbfCode");

                    b.Property<string>("GOExpHist_Entry11InterAmt");

                    b.Property<string>("GOExpHist_Entry11InterRate");

                    b.Property<string>("GOExpHist_Entry11Type");

                    b.Property<string>("GOExpHist_Entry12ActNo");

                    b.Property<string>("GOExpHist_Entry12ActType");

                    b.Property<string>("GOExpHist_Entry12Actcde");

                    b.Property<string>("GOExpHist_Entry12AdvcPrnt");

                    b.Property<string>("GOExpHist_Entry12Amt");

                    b.Property<string>("GOExpHist_Entry12Available");

                    b.Property<string>("GOExpHist_Entry12Ccy");

                    b.Property<string>("GOExpHist_Entry12CheckNo");

                    b.Property<string>("GOExpHist_Entry12Cust");

                    b.Property<string>("GOExpHist_Entry12Details");

                    b.Property<string>("GOExpHist_Entry12Division");

                    b.Property<string>("GOExpHist_Entry12Entity");

                    b.Property<string>("GOExpHist_Entry12ExchCcy");

                    b.Property<string>("GOExpHist_Entry12ExchRate");

                    b.Property<string>("GOExpHist_Entry12Fund");

                    b.Property<string>("GOExpHist_Entry12IbfCode");

                    b.Property<string>("GOExpHist_Entry12InterAmt");

                    b.Property<string>("GOExpHist_Entry12InterRate");

                    b.Property<string>("GOExpHist_Entry12Type");

                    b.Property<string>("GOExpHist_Entry21ActNo");

                    b.Property<string>("GOExpHist_Entry21ActType");

                    b.Property<string>("GOExpHist_Entry21Actcde");

                    b.Property<string>("GOExpHist_Entry21AdvcPrnt");

                    b.Property<string>("GOExpHist_Entry21Amt");

                    b.Property<string>("GOExpHist_Entry21Available");

                    b.Property<string>("GOExpHist_Entry21Ccy");

                    b.Property<string>("GOExpHist_Entry21CheckNo");

                    b.Property<string>("GOExpHist_Entry21Cust");

                    b.Property<string>("GOExpHist_Entry21Details");

                    b.Property<string>("GOExpHist_Entry21Division");

                    b.Property<string>("GOExpHist_Entry21Entity");

                    b.Property<string>("GOExpHist_Entry21ExchCcy");

                    b.Property<string>("GOExpHist_Entry21ExchRate");

                    b.Property<string>("GOExpHist_Entry21Fund");

                    b.Property<string>("GOExpHist_Entry21IbfCode");

                    b.Property<string>("GOExpHist_Entry21InterAmt");

                    b.Property<string>("GOExpHist_Entry21InterRate");

                    b.Property<string>("GOExpHist_Entry21Type");

                    b.Property<string>("GOExpHist_Entry22ActNo");

                    b.Property<string>("GOExpHist_Entry22ActType");

                    b.Property<string>("GOExpHist_Entry22Actcde");

                    b.Property<string>("GOExpHist_Entry22AdvcPrnt");

                    b.Property<string>("GOExpHist_Entry22Amt");

                    b.Property<string>("GOExpHist_Entry22Available");

                    b.Property<string>("GOExpHist_Entry22Ccy");

                    b.Property<string>("GOExpHist_Entry22CheckNo");

                    b.Property<string>("GOExpHist_Entry22Cust");

                    b.Property<string>("GOExpHist_Entry22Details");

                    b.Property<string>("GOExpHist_Entry22Division");

                    b.Property<string>("GOExpHist_Entry22Entity");

                    b.Property<string>("GOExpHist_Entry22ExchCcy");

                    b.Property<string>("GOExpHist_Entry22ExchRate");

                    b.Property<string>("GOExpHist_Entry22Fund");

                    b.Property<string>("GOExpHist_Entry22IbfCode");

                    b.Property<string>("GOExpHist_Entry22InterAmt");

                    b.Property<string>("GOExpHist_Entry22InterRate");

                    b.Property<string>("GOExpHist_Entry22Type");

                    b.Property<string>("GOExpHist_Entry31ActNo");

                    b.Property<string>("GOExpHist_Entry31ActType");

                    b.Property<string>("GOExpHist_Entry31Actcde");

                    b.Property<string>("GOExpHist_Entry31AdvcPrnt");

                    b.Property<string>("GOExpHist_Entry31Amt");

                    b.Property<string>("GOExpHist_Entry31Available");

                    b.Property<string>("GOExpHist_Entry31Ccy");

                    b.Property<string>("GOExpHist_Entry31CheckNo");

                    b.Property<string>("GOExpHist_Entry31Cust");

                    b.Property<string>("GOExpHist_Entry31Details");

                    b.Property<string>("GOExpHist_Entry31Division");

                    b.Property<string>("GOExpHist_Entry31Entity");

                    b.Property<string>("GOExpHist_Entry31ExchCcy");

                    b.Property<string>("GOExpHist_Entry31ExchRate");

                    b.Property<string>("GOExpHist_Entry31Fund");

                    b.Property<string>("GOExpHist_Entry31IbfCode");

                    b.Property<string>("GOExpHist_Entry31InterAmt");

                    b.Property<string>("GOExpHist_Entry31InterRate");

                    b.Property<string>("GOExpHist_Entry31Type");

                    b.Property<string>("GOExpHist_Entry32ActNo");

                    b.Property<string>("GOExpHist_Entry32ActType");

                    b.Property<string>("GOExpHist_Entry32Actcde");

                    b.Property<string>("GOExpHist_Entry32AdvcPrnt");

                    b.Property<string>("GOExpHist_Entry32Amt");

                    b.Property<string>("GOExpHist_Entry32Available");

                    b.Property<string>("GOExpHist_Entry32Ccy");

                    b.Property<string>("GOExpHist_Entry32CheckNo");

                    b.Property<string>("GOExpHist_Entry32Cust");

                    b.Property<string>("GOExpHist_Entry32Details");

                    b.Property<string>("GOExpHist_Entry32Division");

                    b.Property<string>("GOExpHist_Entry32Entity");

                    b.Property<string>("GOExpHist_Entry32ExchCcy");

                    b.Property<string>("GOExpHist_Entry32ExchRate");

                    b.Property<string>("GOExpHist_Entry32Fund");

                    b.Property<string>("GOExpHist_Entry32IbfCode");

                    b.Property<string>("GOExpHist_Entry32InterAmt");

                    b.Property<string>("GOExpHist_Entry32InterRate");

                    b.Property<string>("GOExpHist_Entry32Type");

                    b.Property<string>("GOExpHist_Entry41ActNo");

                    b.Property<string>("GOExpHist_Entry41ActType");

                    b.Property<string>("GOExpHist_Entry41Actcde");

                    b.Property<string>("GOExpHist_Entry41AdvcPrnt");

                    b.Property<string>("GOExpHist_Entry41Amt");

                    b.Property<string>("GOExpHist_Entry41Available");

                    b.Property<string>("GOExpHist_Entry41Ccy");

                    b.Property<string>("GOExpHist_Entry41CheckNo");

                    b.Property<string>("GOExpHist_Entry41Cust");

                    b.Property<string>("GOExpHist_Entry41Details");

                    b.Property<string>("GOExpHist_Entry41Division");

                    b.Property<string>("GOExpHist_Entry41Entity");

                    b.Property<string>("GOExpHist_Entry41ExchCcy");

                    b.Property<string>("GOExpHist_Entry41ExchRate");

                    b.Property<string>("GOExpHist_Entry41Fund");

                    b.Property<string>("GOExpHist_Entry41IbfCode");

                    b.Property<string>("GOExpHist_Entry41InterAmt");

                    b.Property<string>("GOExpHist_Entry41InterRate");

                    b.Property<string>("GOExpHist_Entry41Type");

                    b.Property<string>("GOExpHist_Entry42ActNo");

                    b.Property<string>("GOExpHist_Entry42ActType");

                    b.Property<string>("GOExpHist_Entry42Actcde");

                    b.Property<string>("GOExpHist_Entry42AdvcPrnt");

                    b.Property<string>("GOExpHist_Entry42Amt");

                    b.Property<string>("GOExpHist_Entry42Available");

                    b.Property<string>("GOExpHist_Entry42Ccy");

                    b.Property<string>("GOExpHist_Entry42CheckNo");

                    b.Property<string>("GOExpHist_Entry42Cust");

                    b.Property<string>("GOExpHist_Entry42Details");

                    b.Property<string>("GOExpHist_Entry42Division");

                    b.Property<string>("GOExpHist_Entry42Entity");

                    b.Property<string>("GOExpHist_Entry42ExchCcy");

                    b.Property<string>("GOExpHist_Entry42ExchRate");

                    b.Property<string>("GOExpHist_Entry42Fund");

                    b.Property<string>("GOExpHist_Entry42IbfCode");

                    b.Property<string>("GOExpHist_Entry42InterAmt");

                    b.Property<string>("GOExpHist_Entry42InterRate");

                    b.Property<string>("GOExpHist_Entry42Type");

                    b.Property<string>("GOExpHist_Groupcode");

                    b.Property<string>("GOExpHist_Memo");

                    b.Property<string>("GOExpHist_OpeBranch");

                    b.Property<string>("GOExpHist_OpeKind");

                    b.Property<string>("GOExpHist_ReferenceNo");

                    b.Property<string>("GOExpHist_ReferenceType");

                    b.Property<string>("GOExpHist_Remarks");

                    b.Property<string>("GOExpHist_SchemeNo");

                    b.Property<string>("GOExpHist_Section");

                    b.Property<string>("GOExpHist_SystemName");

                    b.Property<string>("GOExpHist_ValueDate");

                    b.Property<string>("GOExpHist_WarningOverride");

                    b.HasKey("GOExpHist_Id");

                    b.HasIndex("ExpenseEntryModelExpense_ID");

                    b.ToTable("GOExpressHist");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.HomeNotifModel", b =>
                {
                    b.Property<int>("Notif_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Notif_Application_ID");

                    b.Property<DateTime>("Notif_Created_Date");

                    b.Property<DateTime>("Notif_Last_Updated");

                    b.Property<string>("Notif_Message");

                    b.Property<bool>("Notif_Status");

                    b.Property<string>("Notif_Type_Status");

                    b.Property<int>("Notif_User_ID");

                    b.Property<int>("Notif_Verifr_Apprvr_ID");

                    b.HasKey("Notif_ID");

                    b.ToTable("HomeNotif");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.LiquidationCashBreakdownModel", b =>
                {
                    b.Property<int>("LiqCashBreak_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ExpenseEntryDetailModelExpDtl_ID");

                    b.Property<double>("LiqCashBreak_Amount");

                    b.Property<double>("LiqCashBreak_Denomination");

                    b.Property<int>("LiqCashBreak_NoPcs");

                    b.HasKey("LiqCashBreak_ID");

                    b.HasIndex("ExpenseEntryDetailModelExpDtl_ID");

                    b.ToTable("LiquidationCashBreakdown");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.LiquidationEntryDetailModel", b =>
                {
                    b.Property<int>("Liq_DtlID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ExpenseEntryModelExpense_ID");

                    b.Property<int>("Liq_Approver");

                    b.Property<DateTime>("Liq_Created_Date");

                    b.Property<int>("Liq_Created_UserID");

                    b.Property<DateTime>("Liq_LastUpdated_Date");

                    b.Property<int>("Liq_Status");

                    b.Property<int>("Liq_Verifier1");

                    b.Property<int>("Liq_Verifier2");

                    b.HasKey("Liq_DtlID");

                    b.HasIndex("ExpenseEntryModelExpense_ID");

                    b.ToTable("LiquidationEntryDetails");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.LiquidationInterEntityModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ExpenseEntryDetailModelExpDtl_ID");

                    b.Property<string>("Liq_AccountID_1_1");

                    b.Property<string>("Liq_AccountID_1_2");

                    b.Property<string>("Liq_AccountID_2_1");

                    b.Property<string>("Liq_AccountID_2_2");

                    b.Property<string>("Liq_AccountID_3_1");

                    b.Property<string>("Liq_AccountID_3_2");

                    b.Property<double>("Liq_Amount_1_1");

                    b.Property<double>("Liq_Amount_1_2");

                    b.Property<double>("Liq_Amount_2_1");

                    b.Property<double>("Liq_Amount_2_2");

                    b.Property<double>("Liq_Amount_3_1");

                    b.Property<double>("Liq_Amount_3_2");

                    b.Property<string>("Liq_CCY_1_1");

                    b.Property<string>("Liq_CCY_1_2");

                    b.Property<string>("Liq_CCY_2_1");

                    b.Property<string>("Liq_CCY_2_2");

                    b.Property<string>("Liq_CCY_3_1");

                    b.Property<string>("Liq_CCY_3_2");

                    b.Property<string>("Liq_DebitCred_1_1");

                    b.Property<string>("Liq_DebitCred_1_2");

                    b.Property<string>("Liq_DebitCred_2_1");

                    b.Property<string>("Liq_DebitCred_2_2");

                    b.Property<string>("Liq_DebitCred_3_1");

                    b.Property<string>("Liq_DebitCred_3_2");

                    b.Property<double>("Liq_InterRate_1_1");

                    b.Property<double>("Liq_InterRate_1_2");

                    b.Property<double>("Liq_InterRate_2_1");

                    b.Property<double>("Liq_InterRate_2_2");

                    b.Property<double>("Liq_InterRate_3_1");

                    b.Property<double>("Liq_InterRate_3_2");

                    b.HasKey("id");

                    b.HasIndex("ExpenseEntryDetailModelExpDtl_ID");

                    b.ToTable("LiquidationInterEntity");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.PCBreakdownModel", b =>
                {
                    b.Property<int>("PCB_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PCB_Fifty");

                    b.Property<int>("PCB_Five");

                    b.Property<int>("PCB_FiveCents");

                    b.Property<int>("PCB_FiveHundred");

                    b.Property<int>("PCB_One");

                    b.Property<int>("PCB_OneCents");

                    b.Property<int>("PCB_OneHundred");

                    b.Property<int>("PCB_OneThousand");

                    b.Property<int>("PCB_Ten");

                    b.Property<int>("PCB_TenCents");

                    b.Property<int>("PCB_Twenty");

                    b.Property<int>("PCB_TwentyFiveCents");

                    b.Property<int>("PCB_TwoHundred");

                    b.Property<int>("PC_ID");

                    b.HasKey("PCB_ID");

                    b.HasIndex("PC_ID");

                    b.ToTable("PettyCashBreakDown");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.Pending.DMAccountGroupModel_Pending", b =>
                {
                    b.Property<int>("Pending_AccountGroup_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Pending_AccountGroup_Approver_ID");

                    b.Property<string>("Pending_AccountGroup_Code");

                    b.Property<int>("Pending_AccountGroup_Creator_ID");

                    b.Property<DateTime>("Pending_AccountGroup_Filed_Date");

                    b.Property<int>("Pending_AccountGroup_MasterID");

                    b.Property<string>("Pending_AccountGroup_Name");

                    b.Property<int>("Pending_AccountGroup_Status_ID");

                    b.Property<bool>("Pending_AccountGroup_isActive");

                    b.Property<bool>("Pending_AccountGroup_isDeleted");

                    b.HasKey("Pending_AccountGroup_ID");

                    b.ToTable("DMAccountGroup_Pending");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.Pending.DMBIRCertSignModel_Pending", b =>
                {
                    b.Property<int>("Pending_BCS_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Pending_BCS_Approver_ID");

                    b.Property<int>("Pending_BCS_Creator_ID");

                    b.Property<DateTime>("Pending_BCS_Filed_Date");

                    b.Property<int>("Pending_BCS_MasterID");

                    b.Property<string>("Pending_BCS_Name");

                    b.Property<string>("Pending_BCS_Position");

                    b.Property<string>("Pending_BCS_Signatures");

                    b.Property<int>("Pending_BCS_Status_ID");

                    b.Property<string>("Pending_BCS_TIN");

                    b.Property<bool>("Pending_BCS_isActive");

                    b.Property<bool>("Pending_BCS_isDeleted");

                    b.HasKey("Pending_BCS_ID");

                    b.ToTable("DMBCS_Pending");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.Pending.DMCurrencyModel_Pending", b =>
                {
                    b.Property<int>("Pending_Curr_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Pending_Curr_Approver_ID");

                    b.Property<string>("Pending_Curr_CCY_ABBR");

                    b.Property<int>("Pending_Curr_Creator_ID");

                    b.Property<DateTime>("Pending_Curr_Filed_Date");

                    b.Property<int>("Pending_Curr_MasterID");

                    b.Property<string>("Pending_Curr_Name");

                    b.Property<int>("Pending_Curr_Status_ID");

                    b.Property<bool>("Pending_Curr_isActive");

                    b.Property<bool>("Pending_Curr_isDeleted");

                    b.HasKey("Pending_Curr_ID");

                    b.ToTable("DMCurrency_Pending");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.Pending.DMCustModel_Pending", b =>
                {
                    b.Property<int>("Pending_Cust_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Pending_Cust_Abbr");

                    b.Property<int>("Pending_Cust_Approver_ID");

                    b.Property<int>("Pending_Cust_Creator_ID");

                    b.Property<DateTime>("Pending_Cust_Filed_Date");

                    b.Property<int>("Pending_Cust_MasterID");

                    b.Property<string>("Pending_Cust_Name");

                    b.Property<string>("Pending_Cust_No");

                    b.Property<int>("Pending_Cust_Status_ID");

                    b.Property<bool>("Pending_Cust_isActive");

                    b.Property<bool>("Pending_Cust_isDeleted");

                    b.HasKey("Pending_Cust_ID");

                    b.ToTable("DMCust_Pending");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.Pending.DMEmpModel_Pending", b =>
                {
                    b.Property<int>("Pending_Emp_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Pending_Emp_Acc_No");

                    b.Property<int>("Pending_Emp_Approver_ID");

                    b.Property<int>("Pending_Emp_Creator_ID");

                    b.Property<DateTime>("Pending_Emp_Filed_Date");

                    b.Property<int>("Pending_Emp_MasterID");

                    b.Property<string>("Pending_Emp_Name");

                    b.Property<int>("Pending_Emp_Status_ID");

                    b.Property<string>("Pending_Emp_Type");

                    b.Property<bool>("Pending_Emp_isActive");

                    b.Property<bool>("Pending_Emp_isDeleted");

                    b.HasKey("Pending_Emp_ID");

                    b.ToTable("DMEmp_Pending");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.Pending.DMFBTModel_Pending", b =>
                {
                    b.Property<int>("Pending_FBT_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Pending_FBT_Approver_ID");

                    b.Property<int>("Pending_FBT_Creator_ID");

                    b.Property<DateTime>("Pending_FBT_Filed_Date");

                    b.Property<string>("Pending_FBT_Formula");

                    b.Property<int>("Pending_FBT_MasterID");

                    b.Property<string>("Pending_FBT_Name");

                    b.Property<int>("Pending_FBT_Status_ID");

                    b.Property<float>("Pending_FBT_Tax_Rate");

                    b.Property<bool>("Pending_FBT_isActive");

                    b.Property<bool>("Pending_FBT_isDeleted");

                    b.HasKey("Pending_FBT_ID");

                    b.ToTable("DMFBT_Pending");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.Pending.DMTRModel_Pending", b =>
                {
                    b.Property<int>("Pending_TR_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Pending_TR_ATC");

                    b.Property<int>("Pending_TR_Approver_ID");

                    b.Property<int>("Pending_TR_Creator_ID");

                    b.Property<DateTime>("Pending_TR_Filed_Date");

                    b.Property<int>("Pending_TR_MasterID");

                    b.Property<string>("Pending_TR_Nature");

                    b.Property<string>("Pending_TR_Nature_Income_Payment");

                    b.Property<int>("Pending_TR_Status_ID");

                    b.Property<float>("Pending_TR_Tax_Rate");

                    b.Property<string>("Pending_TR_WT_Title");

                    b.Property<bool>("Pending_TR_isActive");

                    b.Property<bool>("Pending_TR_isDeleted");

                    b.HasKey("Pending_TR_ID");

                    b.ToTable("DMTR_Pending");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.Pending.DMVATModel_Pending", b =>
                {
                    b.Property<int>("Pending_VAT_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Pending_VAT_Approver_ID");

                    b.Property<int>("Pending_VAT_Creator_ID");

                    b.Property<DateTime>("Pending_VAT_Filed_Date");

                    b.Property<int>("Pending_VAT_MasterID");

                    b.Property<string>("Pending_VAT_Name");

                    b.Property<float>("Pending_VAT_Rate");

                    b.Property<int>("Pending_VAT_Status_ID");

                    b.Property<bool>("Pending_VAT_isActive");

                    b.Property<bool>("Pending_VAT_isDeleted");

                    b.HasKey("Pending_VAT_ID");

                    b.ToTable("DMVAT_Pending");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.Pending.DMVendorTRVATModel_Pending", b =>
                {
                    b.Property<int>("Pending_VTV_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Pending_VTV_Status_ID");

                    b.Property<int>("Pending_VTV_TR_ID");

                    b.Property<int>("Pending_VTV_VAT_ID");

                    b.Property<int>("Pending_VTV_Vendor_ID");

                    b.HasKey("Pending_VTV_ID");

                    b.ToTable("DMVendorTRVAT_Pending");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.PettyCashModel", b =>
                {
                    b.Property<int>("PC_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PC_CloseUser");

                    b.Property<string>("PC_ConfirmComment");

                    b.Property<DateTime>("PC_Date");

                    b.Property<double>("PC_Disbursed");

                    b.Property<double>("PC_EndBal");

                    b.Property<bool>("PC_OpenConfirm");

                    b.Property<int>("PC_OpenUser");

                    b.Property<double>("PC_StartBal");

                    b.HasKey("PC_ID");

                    b.ToTable("PettyCash");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.StatusListModel", b =>
                {
                    b.Property<int>("Status_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status_Name");

                    b.HasKey("Status_ID");

                    b.ToTable("StatusList");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.SystemMessageModel", b =>
                {
                    b.Property<string>("Msg_Code")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Msg_Content");

                    b.Property<string>("Msg_Type");

                    b.HasKey("Msg_Code");

                    b.ToTable("SystemMessageModels");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.UserModel", b =>
                {
                    b.Property<int>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("User_Approver_ID");

                    b.Property<string>("User_Comment");

                    b.Property<DateTime>("User_Created_Date");

                    b.Property<int>("User_Creator_ID");

                    b.Property<int>("User_DeptID");

                    b.Property<string>("User_Email");

                    b.Property<string>("User_FName");

                    b.Property<bool>("User_InUse");

                    b.Property<string>("User_LName");

                    b.Property<DateTime>("User_Last_Updated");

                    b.Property<string>("User_Password");

                    b.Property<string>("User_Role");

                    b.Property<string>("User_Status");

                    b.Property<string>("User_UserName");

                    b.HasKey("User_ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.ExpenseEntryAmortizationModel", b =>
                {
                    b.HasOne("ExpenseProcessingSystem.Models.ExpenseEntryDetailModel", "ExpenseEntryDetailModel")
                        .WithMany("ExpenseEntryAmortizations")
                        .HasForeignKey("ExpenseEntryDetailModelExpDtl_ID");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.ExpenseEntryCashBreakdownModel", b =>
                {
                    b.HasOne("ExpenseProcessingSystem.Models.ExpenseEntryDetailModel", "ExpenseEntryDetailModel")
                        .WithMany("ExpenseEntryCashBreakdowns")
                        .HasForeignKey("ExpenseEntryDetailModelExpDtl_ID");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.ExpenseEntryDetailModel", b =>
                {
                    b.HasOne("ExpenseProcessingSystem.Models.ExpenseEntryModel", "ExpenseEntryModel")
                        .WithMany("ExpenseEntryDetails")
                        .HasForeignKey("ExpenseEntryModelExpense_ID");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.ExpenseEntryGbaseDtl", b =>
                {
                    b.HasOne("ExpenseProcessingSystem.Models.ExpenseEntryDetailModel", "ExpenseEntryDetailModel")
                        .WithMany("ExpenseEntryGbaseDtls")
                        .HasForeignKey("ExpenseEntryDetailModelExpDtl_ID");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.ExpenseEntryInterEntityAccsModel", b =>
                {
                    b.HasOne("ExpenseProcessingSystem.Models.ExpenseEntryInterEntityParticularModel", "ExpenseEntryInterEntityParticular")
                        .WithMany("ExpenseEntryInterEntityAccs")
                        .HasForeignKey("ExpenseEntryInterEntityParticularInterPart_ID");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.ExpenseEntryInterEntityModel", b =>
                {
                    b.HasOne("ExpenseProcessingSystem.Models.ExpenseEntryDetailModel", "ExpenseEntryDetailModel")
                        .WithMany("ExpenseEntryInterEntity")
                        .HasForeignKey("ExpenseEntryDetailModelExpDtl_ID");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.ExpenseEntryInterEntityParticularModel", b =>
                {
                    b.HasOne("ExpenseProcessingSystem.Models.ExpenseEntryInterEntityModel", "ExpenseEntryInterEntityModel")
                        .WithMany("ExpenseEntryInterEntityParticular")
                        .HasForeignKey("ExpenseEntryInterEntityModelExpDtl_DDVInter_ID");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.ExpenseEntryNCDtlAccModel", b =>
                {
                    b.HasOne("ExpenseProcessingSystem.Models.ExpenseEntryNCDtlModel", "ExpenseEntryNCDtlModel")
                        .WithMany("ExpenseEntryNCDtlAccs")
                        .HasForeignKey("ExpenseEntryNCDtlModelExpNCDtl_ID");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.ExpenseEntryNCDtlModel", b =>
                {
                    b.HasOne("ExpenseProcessingSystem.Models.ExpenseEntryNCModel", "ExpenseEntryNCModel")
                        .WithMany("ExpenseEntryNCDtls")
                        .HasForeignKey("ExpenseEntryNCModelExpNC_ID");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.ExpenseEntryNCModel", b =>
                {
                    b.HasOne("ExpenseProcessingSystem.Models.ExpenseEntryModel", "ExpenseEntryModel")
                        .WithMany("ExpenseEntryNC")
                        .HasForeignKey("ExpenseEntryModelExpense_ID");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.GOExpressHistModel", b =>
                {
                    b.HasOne("ExpenseProcessingSystem.Models.ExpenseEntryModel", "ExpenseEntryModel")
                        .WithMany()
                        .HasForeignKey("ExpenseEntryModelExpense_ID");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.LiquidationCashBreakdownModel", b =>
                {
                    b.HasOne("ExpenseProcessingSystem.Models.ExpenseEntryDetailModel", "ExpenseEntryDetailModel")
                        .WithMany()
                        .HasForeignKey("ExpenseEntryDetailModelExpDtl_ID");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.LiquidationEntryDetailModel", b =>
                {
                    b.HasOne("ExpenseProcessingSystem.Models.ExpenseEntryModel", "ExpenseEntryModel")
                        .WithMany()
                        .HasForeignKey("ExpenseEntryModelExpense_ID");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.LiquidationInterEntityModel", b =>
                {
                    b.HasOne("ExpenseProcessingSystem.Models.ExpenseEntryDetailModel", "ExpenseEntryDetailModel")
                        .WithMany()
                        .HasForeignKey("ExpenseEntryDetailModelExpDtl_ID");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.PCBreakdownModel", b =>
                {
                    b.HasOne("ExpenseProcessingSystem.Models.PettyCashModel", "PettyCashObject")
                        .WithMany("PCBreakdown")
                        .HasForeignKey("PC_ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
