using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace ExpenseProcessingSystem.Migrations
{
    public partial class GOExpressHist : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "GOExpressHist",
                columns: table => new
                {
                    GOExpHist_Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    GOExpHist_SystemName = table.Column<string>(nullable: true),
                    GOExpHist_Groupcode = table.Column<string>(nullable: true),
                    GOExpHist_Branchno = table.Column<string>(nullable: true),
                    GOExpHist_OpeKind = table.Column<string>(nullable: true),
                    GOExpHist_AutoApproved = table.Column<string>(nullable: true),
                    GOExpHist_WarningOverride = table.Column<string>(nullable: true),
                    GOExpHist_CcyFormat = table.Column<string>(nullable: true),
                    GOExpHist_OpeBranch = table.Column<string>(nullable: true),
                    GOExpHist_ValueDate = table.Column<string>(nullable: true),
                    GOExpHist_ReferenceType = table.Column<string>(nullable: true),
                    GOExpHist_ReferenceNo = table.Column<string>(nullable: true),
                    GOExpHist_Comment = table.Column<string>(nullable: true),
                    GOExpHist_Section = table.Column<string>(nullable: true),
                    GOExpHist_Remarks = table.Column<string>(nullable: true),
                    GOExpHist_Memo = table.Column<string>(nullable: true),
                    GOExpHist_SchemeNo = table.Column<string>(nullable: true),
                    GOExpHist_Entry11Type = table.Column<string>(nullable: true),
                    GOExpHist_Entry11IbfCode = table.Column<string>(nullable: true),
                    GOExpHist_Entry11Ccy = table.Column<string>(nullable: true),
                    GOExpHist_Entry11Amt = table.Column<string>(nullable: true),
                    GOExpHist_Entry11Cust = table.Column<string>(nullable: true),
                    GOExpHist_Entry11Actcde = table.Column<string>(nullable: true),
                    GOExpHist_Entry11ActType = table.Column<string>(nullable: true),
                    GOExpHist_Entry11ActNo = table.Column<string>(nullable: true),
                    GOExpHist_Entry11ExchRate = table.Column<string>(nullable: true),
                    GOExpHist_Entry11ExchCcy = table.Column<string>(nullable: true),
                    GOExpHist_Entry11Fund = table.Column<string>(nullable: true),
                    GOExpHist_Entry11CheckNo = table.Column<string>(nullable: true),
                    GOExpHist_Entry11Available = table.Column<string>(nullable: true),
                    GOExpHist_Entry11AdvcPrnt = table.Column<string>(nullable: true),
                    GOExpHist_Entry11Details = table.Column<string>(nullable: true),
                    GOExpHist_Entry11Entity = table.Column<string>(nullable: true),
                    GOExpHist_Entry11Division = table.Column<string>(nullable: true),
                    GOExpHist_Entry11InterAmt = table.Column<string>(nullable: true),
                    GOExpHist_Entry11InterRate = table.Column<string>(nullable: true),
                    GOExpHist_Entry12Type = table.Column<string>(nullable: true),
                    GOExpHist_Entry12IbfCode = table.Column<string>(nullable: true),
                    GOExpHist_Entry12Ccy = table.Column<string>(nullable: true),
                    GOExpHist_Entry12Amt = table.Column<string>(nullable: true),
                    GOExpHist_Entry12Cust = table.Column<string>(nullable: true),
                    GOExpHist_Entry12Actcde = table.Column<string>(nullable: true),
                    GOExpHist_Entry12ActType = table.Column<string>(nullable: true),
                    GOExpHist_Entry12ActNo = table.Column<string>(nullable: true),
                    GOExpHist_Entry12ExchRate = table.Column<string>(nullable: true),
                    GOExpHist_Entry12ExchCcy = table.Column<string>(nullable: true),
                    GOExpHist_Entry12Fund = table.Column<string>(nullable: true),
                    GOExpHist_Entry12CheckNo = table.Column<string>(nullable: true),
                    GOExpHist_Entry12Available = table.Column<string>(nullable: true),
                    GOExpHist_Entry12AdvcPrnt = table.Column<string>(nullable: true),
                    GOExpHist_Entry12Details = table.Column<string>(nullable: true),
                    GOExpHist_Entry12Entity = table.Column<string>(nullable: true),
                    GOExpHist_Entry12Division = table.Column<string>(nullable: true),
                    GOExpHist_Entry12InterAmt = table.Column<string>(nullable: true),
                    GOExpHist_Entry12InterRate = table.Column<string>(nullable: true),
                    GOExpHist_Entry21Type = table.Column<string>(nullable: true),
                    GOExpHist_Entry21IbfCode = table.Column<string>(nullable: true),
                    GOExpHist_Entry21Ccy = table.Column<string>(nullable: true),
                    GOExpHist_Entry21Amt = table.Column<string>(nullable: true),
                    GOExpHist_Entry21Cust = table.Column<string>(nullable: true),
                    GOExpHist_Entry21Actcde = table.Column<string>(nullable: true),
                    GOExpHist_Entry21ActType = table.Column<string>(nullable: true),
                    GOExpHist_Entry21ActNo = table.Column<string>(nullable: true),
                    GOExpHist_Entry21ExchRate = table.Column<string>(nullable: true),
                    GOExpHist_Entry21ExchCcy = table.Column<string>(nullable: true),
                    GOExpHist_Entry21Fund = table.Column<string>(nullable: true),
                    GOExpHist_Entry21CheckNo = table.Column<string>(nullable: true),
                    GOExpHist_Entry21Available = table.Column<string>(nullable: true),
                    GOExpHist_Entry21AdvcPrnt = table.Column<string>(nullable: true),
                    GOExpHist_Entry21Details = table.Column<string>(nullable: true),
                    GOExpHist_Entry21Entity = table.Column<string>(nullable: true),
                    GOExpHist_Entry21Division = table.Column<string>(nullable: true),
                    GOExpHist_Entry21InterAmt = table.Column<string>(nullable: true),
                    GOExpHist_Entry21InterRate = table.Column<string>(nullable: true),
                    GOExpHist_Entry22Type = table.Column<string>(nullable: true),
                    GOExpHist_Entry22IbfCode = table.Column<string>(nullable: true),
                    GOExpHist_Entry22Ccy = table.Column<string>(nullable: true),
                    GOExpHist_Entry22Amt = table.Column<string>(nullable: true),
                    GOExpHist_Entry22Cust = table.Column<string>(nullable: true),
                    GOExpHist_Entry22Actcde = table.Column<string>(nullable: true),
                    GOExpHist_Entry22ActType = table.Column<string>(nullable: true),
                    GOExpHist_Entry22ActNo = table.Column<string>(nullable: true),
                    GOExpHist_Entry22ExchRate = table.Column<string>(nullable: true),
                    GOExpHist_Entry22ExchCcy = table.Column<string>(nullable: true),
                    GOExpHist_Entry22Fund = table.Column<string>(nullable: true),
                    GOExpHist_Entry22CheckNo = table.Column<string>(nullable: true),
                    GOExpHist_Entry22Available = table.Column<string>(nullable: true),
                    GOExpHist_Entry22AdvcPrnt = table.Column<string>(nullable: true),
                    GOExpHist_Entry22Details = table.Column<string>(nullable: true),
                    GOExpHist_Entry22Entity = table.Column<string>(nullable: true),
                    GOExpHist_Entry22Division = table.Column<string>(nullable: true),
                    GOExpHist_Entry22InterAmt = table.Column<string>(nullable: true),
                    GOExpHist_Entry22InterRate = table.Column<string>(nullable: true),
                    GOExpHist_Entry31Type = table.Column<string>(nullable: true),
                    GOExpHist_Entry31IbfCode = table.Column<string>(nullable: true),
                    GOExpHist_Entry31Ccy = table.Column<string>(nullable: true),
                    GOExpHist_Entry31Amt = table.Column<string>(nullable: true),
                    GOExpHist_Entry31Cust = table.Column<string>(nullable: true),
                    GOExpHist_Entry31Actcde = table.Column<string>(nullable: true),
                    GOExpHist_Entry31ActType = table.Column<string>(nullable: true),
                    GOExpHist_Entry31ActNo = table.Column<string>(nullable: true),
                    GOExpHist_Entry31ExchRate = table.Column<string>(nullable: true),
                    GOExpHist_Entry31ExchCcy = table.Column<string>(nullable: true),
                    GOExpHist_Entry31Fund = table.Column<string>(nullable: true),
                    GOExpHist_Entry31CheckNo = table.Column<string>(nullable: true),
                    GOExpHist_Entry31Available = table.Column<string>(nullable: true),
                    GOExpHist_Entry31AdvcPrnt = table.Column<string>(nullable: true),
                    GOExpHist_Entry31Details = table.Column<string>(nullable: true),
                    GOExpHist_Entry31Entity = table.Column<string>(nullable: true),
                    GOExpHist_Entry31Division = table.Column<string>(nullable: true),
                    GOExpHist_Entry31InterAmt = table.Column<string>(nullable: true),
                    GOExpHist_Entry31InterRate = table.Column<string>(nullable: true),
                    GOExpHist_Entry32Type = table.Column<string>(nullable: true),
                    GOExpHist_Entry32IbfCode = table.Column<string>(nullable: true),
                    GOExpHist_Entry32Ccy = table.Column<string>(nullable: true),
                    GOExpHist_Entry32Amt = table.Column<string>(nullable: true),
                    GOExpHist_Entry32Cust = table.Column<string>(nullable: true),
                    GOExpHist_Entry32Actcde = table.Column<string>(nullable: true),
                    GOExpHist_Entry32ActType = table.Column<string>(nullable: true),
                    GOExpHist_Entry32ActNo = table.Column<string>(nullable: true),
                    GOExpHist_Entry32ExchRate = table.Column<string>(nullable: true),
                    GOExpHist_Entry32ExchCcy = table.Column<string>(nullable: true),
                    GOExpHist_Entry32Fund = table.Column<string>(nullable: true),
                    GOExpHist_Entry32CheckNo = table.Column<string>(nullable: true),
                    GOExpHist_Entry32Available = table.Column<string>(nullable: true),
                    GOExpHist_Entry32AdvcPrnt = table.Column<string>(nullable: true),
                    GOExpHist_Entry32Details = table.Column<string>(nullable: true),
                    GOExpHist_Entry32Entity = table.Column<string>(nullable: true),
                    GOExpHist_Entry32Division = table.Column<string>(nullable: true),
                    GOExpHist_Entry32InterAmt = table.Column<string>(nullable: true),
                    GOExpHist_Entry32InterRate = table.Column<string>(nullable: true),
                    GOExpHist_Entry41Type = table.Column<string>(nullable: true),
                    GOExpHist_Entry41IbfCode = table.Column<string>(nullable: true),
                    GOExpHist_Entry41Ccy = table.Column<string>(nullable: true),
                    GOExpHist_Entry41Amt = table.Column<string>(nullable: true),
                    GOExpHist_Entry41Cust = table.Column<string>(nullable: true),
                    GOExpHist_Entry41Actcde = table.Column<string>(nullable: true),
                    GOExpHist_Entry41ActType = table.Column<string>(nullable: true),
                    GOExpHist_Entry41ActNo = table.Column<string>(nullable: true),
                    GOExpHist_Entry41ExchRate = table.Column<string>(nullable: true),
                    GOExpHist_Entry41ExchCcy = table.Column<string>(nullable: true),
                    GOExpHist_Entry41Fund = table.Column<string>(nullable: true),
                    GOExpHist_Entry41CheckNo = table.Column<string>(nullable: true),
                    GOExpHist_Entry41Available = table.Column<string>(nullable: true),
                    GOExpHist_Entry41AdvcPrnt = table.Column<string>(nullable: true),
                    GOExpHist_Entry41Details = table.Column<string>(nullable: true),
                    GOExpHist_Entry41Entity = table.Column<string>(nullable: true),
                    GOExpHist_Entry41Division = table.Column<string>(nullable: true),
                    GOExpHist_Entry41InterAmt = table.Column<string>(nullable: true),
                    GOExpHist_Entry41InterRate = table.Column<string>(nullable: true),
                    GOExpHist_Entry42Type = table.Column<string>(nullable: true),
                    GOExpHist_Entry42IbfCode = table.Column<string>(nullable: true),
                    GOExpHist_Entry42Ccy = table.Column<string>(nullable: true),
                    GOExpHist_Entry42Amt = table.Column<string>(nullable: true),
                    GOExpHist_Entry42Cust = table.Column<string>(nullable: true),
                    GOExpHist_Entry42Actcde = table.Column<string>(nullable: true),
                    GOExpHist_Entry42ActType = table.Column<string>(nullable: true),
                    GOExpHist_Entry42ActNo = table.Column<string>(nullable: true),
                    GOExpHist_Entry42ExchRate = table.Column<string>(nullable: true),
                    GOExpHist_Entry42ExchCcy = table.Column<string>(nullable: true),
                    GOExpHist_Entry42Fund = table.Column<string>(nullable: true),
                    GOExpHist_Entry42CheckNo = table.Column<string>(nullable: true),
                    GOExpHist_Entry42Available = table.Column<string>(nullable: true),
                    GOExpHist_Entry42AdvcPrnt = table.Column<string>(nullable: true),
                    GOExpHist_Entry42Details = table.Column<string>(nullable: true),
                    GOExpHist_Entry42Entity = table.Column<string>(nullable: true),
                    GOExpHist_Entry42Division = table.Column<string>(nullable: true),
                    GOExpHist_Entry42InterAmt = table.Column<string>(nullable: true),
                    GOExpHist_Entry42InterRate = table.Column<string>(nullable: true),
                    ExpenseEntryModelExpense_ID = table.Column<int>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_GOExpressHist", x => x.GOExpHist_Id);
                    table.ForeignKey(
                        name: "FK_GOExpressHist_ExpenseEntry_ExpenseEntryModelExpense_ID",
                        column: x => x.ExpenseEntryModelExpense_ID,
                        principalTable: "ExpenseEntry",
                        principalColumn: "Expense_ID",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_GOExpressHist_ExpenseEntryModelExpense_ID",
                table: "GOExpressHist",
                column: "ExpenseEntryModelExpense_ID");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "GOExpressHist");
        }
    }
}
