// <auto-generated />
using System;
using ExpenseProcessingSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExpenseProcessingSystem.Migrations
{
    [DbContext(typeof(EPSDbContext))]
    [Migration("20190315045339_AddPendingPayeeTable")]
    partial class AddPendingPayeeTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExpenseProcessingSystem.Models.BudgetModel", b =>
                {
                    b.Property<int>("Budget_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Budget_Acc_ID");

                    b.Property<string>("Budget_Amount");

                    b.Property<int>("Budget_Approver_ID");

                    b.Property<DateTime>("Budget_Created_Date");

                    b.Property<int>("Budget_Creator_ID");

                    b.Property<DateTime>("Budget_Last_Updated");

                    b.Property<string>("Budget_Status");

                    b.Property<bool>("Budget_isDeleted");

                    b.HasKey("Budget_ID");

                    b.ToTable("Budget");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.DMAccountModel", b =>
                {
                    b.Property<int>("Account_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Account_Approver_ID");

                    b.Property<string>("Account_Code");

                    b.Property<DateTime>("Account_Created_Date");

                    b.Property<int>("Account_Creator_ID");

                    b.Property<string>("Account_Cust");

                    b.Property<string>("Account_Div");

                    b.Property<string>("Account_Fund");

                    b.Property<DateTime>("Account_Last_Updated");

                    b.Property<string>("Account_Name");

                    b.Property<int>("Account_No");

                    b.Property<string>("Account_Status");

                    b.Property<bool>("Account_isDeleted");

                    b.HasKey("Account_ID");

                    b.ToTable("DMAccount");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.DMCheckModel", b =>
                {
                    b.Property<int>("Check_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Check_Approver_ID");

                    b.Property<DateTime>("Check_Created_Date");

                    b.Property<int>("Check_Creator_ID");

                    b.Property<DateTime>("Check_Input_Date");

                    b.Property<DateTime>("Check_Last_Updated");

                    b.Property<string>("Check_Name");

                    b.Property<string>("Check_Series_From");

                    b.Property<string>("Check_Series_To");

                    b.Property<string>("Check_Status");

                    b.Property<string>("Check_Type");

                    b.Property<bool>("Check_isDeleted");

                    b.HasKey("Check_ID");

                    b.ToTable("DMCheck");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.DMCurrencyModel", b =>
                {
                    b.Property<int>("Curr_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Curr_Approver_ID");

                    b.Property<string>("Curr_CCY_Code");

                    b.Property<DateTime>("Curr_Created_Date");

                    b.Property<int>("Curr_Creator_ID");

                    b.Property<DateTime>("Curr_Last_Updated");

                    b.Property<string>("Curr_Name");

                    b.Property<string>("Curr_Status");

                    b.Property<bool>("Curr_isDeleted");

                    b.HasKey("Curr_ID");

                    b.ToTable("DMCurrency");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.DMDeptModel", b =>
                {
                    b.Property<int>("Dept_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Dept_Approver_ID");

                    b.Property<string>("Dept_Code");

                    b.Property<DateTime>("Dept_Created_Date");

                    b.Property<int>("Dept_Creator_ID");

                    b.Property<DateTime>("Dept_Last_Updated");

                    b.Property<string>("Dept_Name");

                    b.Property<string>("Dept_Status");

                    b.Property<bool>("Dept_isDeleted");

                    b.HasKey("Dept_ID");

                    b.ToTable("DMDept");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.DMEWTModel", b =>
                {
                    b.Property<int>("EWT_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EWT_ATC");

                    b.Property<int>("EWT_Approver_ID");

                    b.Property<DateTime>("EWT_Created_Date");

                    b.Property<int>("EWT_Creator_ID");

                    b.Property<DateTime>("EWT_Last_Updated");

                    b.Property<string>("EWT_Nature");

                    b.Property<string>("EWT_Status");

                    b.Property<int>("EWT_Tax_Rate");

                    b.Property<string>("EWT_Tax_Rate_Desc");

                    b.Property<bool>("EWT_isDeleted");

                    b.HasKey("EWT_ID");

                    b.ToTable("DMEWT");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.DMFBTModel", b =>
                {
                    b.Property<int>("FBT_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FBT_Account");

                    b.Property<int>("FBT_Approver_ID");

                    b.Property<DateTime>("FBT_Created_Date");

                    b.Property<int>("FBT_Creator_ID");

                    b.Property<string>("FBT_Formula");

                    b.Property<DateTime>("FBT_Last_Updated");

                    b.Property<string>("FBT_Name");

                    b.Property<string>("FBT_Status");

                    b.Property<int>("FBT_Tax_Rate");

                    b.Property<bool>("FBT_isDeleted");

                    b.HasKey("FBT_ID");

                    b.ToTable("DMFBT");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.DMPayeeModel", b =>
                {
                    b.Property<int>("Payee_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Payee_Address");

                    b.Property<int>("Payee_Approver_ID");

                    b.Property<DateTime>("Payee_Created_Date");

                    b.Property<int>("Payee_Creator_ID");

                    b.Property<DateTime>("Payee_Last_Updated");

                    b.Property<string>("Payee_Name");

                    b.Property<int>("Payee_No");

                    b.Property<string>("Payee_Status");

                    b.Property<string>("Payee_TIN");

                    b.Property<string>("Payee_Type");

                    b.Property<bool>("Payee_isDeleted");

                    b.HasKey("Payee_ID");

                    b.ToTable("DMPayee");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.DMPayeeModel_Pending", b =>
                {
                    b.Property<int>("Pending_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Payee_ID");

                    b.Property<string>("Pending_Payee_Address");

                    b.Property<int>("Pending_Payee_Creator_ID");

                    b.Property<DateTime>("Pending_Payee_Filed_Date");

                    b.Property<int>("Pending_Payee_ID");

                    b.Property<string>("Pending_Payee_Name");

                    b.Property<int>("Pending_Payee_No");

                    b.Property<string>("Pending_Payee_Status");

                    b.Property<string>("Pending_Payee_TIN");

                    b.Property<string>("Pending_Payee_Type");

                    b.HasKey("Pending_ID");

                    b.HasIndex("Payee_ID");

                    b.ToTable("DMPayee_Pending");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.DMVATModel", b =>
                {
                    b.Property<int>("VAT_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("VAT_Approver_ID");

                    b.Property<DateTime>("VAT_Created_Date");

                    b.Property<int>("VAT_Creator_ID");

                    b.Property<DateTime>("VAT_Last_Updated");

                    b.Property<string>("VAT_Name");

                    b.Property<string>("VAT_Rate");

                    b.Property<string>("VAT_Status");

                    b.Property<bool>("VAT_isDeleted");

                    b.HasKey("VAT_ID");

                    b.ToTable("DMVAT");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.SystemMessageModel", b =>
                {
                    b.Property<string>("Msg_Code")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Msg_Content");

                    b.Property<string>("Msg_Type");

                    b.HasKey("Msg_Code");

                    b.ToTable("SystemMessageModels");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.UserModel", b =>
                {
                    b.Property<int>("Acc_UserID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Acc_Approver_ID");

                    b.Property<string>("Acc_Comment");

                    b.Property<DateTime>("Acc_Created_Date");

                    b.Property<int>("Acc_Creator_ID");

                    b.Property<int>("Acc_DeptID");

                    b.Property<string>("Acc_Email");

                    b.Property<string>("Acc_FName");

                    b.Property<bool>("Acc_InUse");

                    b.Property<string>("Acc_LName");

                    b.Property<DateTime>("Acc_Last_Updated");

                    b.Property<string>("Acc_Password");

                    b.Property<string>("Acc_Role");

                    b.Property<string>("Acc_Status");

                    b.Property<string>("Acc_UserName");

                    b.HasKey("Acc_UserID");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.DMPayeeModel_Pending", b =>
                {
                    b.HasOne("ExpenseProcessingSystem.Models.DMPayeeModel", "Payee")
                        .WithMany("Payee_Pending")
                        .HasForeignKey("Payee_ID");
                });
#pragma warning restore 612, 618
        }
    }
}
