// <auto-generated />
using System;
using ExpenseProcessingSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExpenseProcessingSystem.Migrations.GoWrite
{
    [DbContext(typeof(GoWriteContext))]
    partial class GoWriteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExpenseProcessingSystem.Models.Gbase.tblRequest_DetailsModel", b =>
                {
                    b.Property<int>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Priority");

                    b.Property<string>("RacfID");

                    b.Property<string>("RacfPassword");

                    b.Property<DateTime>("RequestCreated");

                    b.Property<string>("ReturnMessage");

                    b.Property<string>("Status");

                    b.Property<DateTime>("StatusDate");

                    b.Property<string>("SystemAbbr");

                    b.HasKey("RequestID");

                    b.ToTable("tblRequest_Details");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.Gbase.tblRequest_ItemModel", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Command");

                    b.Property<int>("RequestID");

                    b.Property<bool>("ReturnFlag");

                    b.Property<string>("ScreenCapture");

                    b.Property<int>("SequenceNo");

                    b.HasKey("ItemID");

                    b.HasIndex("RequestID");

                    b.ToTable("tblRequest_Item");
                });

            modelBuilder.Entity("ExpenseProcessingSystem.Models.Gbase.tblRequest_ItemModel", b =>
                {
                    b.HasOne("ExpenseProcessingSystem.Models.Gbase.tblRequest_DetailsModel", "Request_Details")
                        .WithMany("Request_Item")
                        .HasForeignKey("RequestID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
