using System;
using System.Collections.Generic;

namespace ExpenseProcessingSystem.Models.Gbase
{
    public partial class TblCm10
    {
        public decimal Id { get; set; }
        public string SystemName { get; set; }
        public string Groupcode { get; set; }
        public string Branchno { get; set; }
        public string OpeKind { get; set; }
        public string AutoApproved { get; set; }
        public string WarningOverride { get; set; }
        public string CcyFormat { get; set; }
        public string OpeBranch { get; set; }
        public string ValueDate { get; set; }
        public string ReferenceType { get; set; }
        public string ReferenceNo { get; set; }
        public string Comment { get; set; }
        public string Section { get; set; }
        public string Remarks { get; set; }
        public string Memo { get; set; }
        public string SchemeNo { get; set; }
        public string Entry11Type { get; set; }
        public string Entry11IbfCode { get; set; }
        public string Entry11Ccy { get; set; }
        public string Entry11Amt { get; set; }
        public string Entry11Cust { get; set; }
        public string Entry11Actcde { get; set; }
        public string Entry11ActType { get; set; }
        public string Entry11ActNo { get; set; }
        public string Entry11ExchRate { get; set; }
        public string Entry11ExchCcy { get; set; }
        public string Entry11Fund { get; set; }
        public string Entry11CheckNo { get; set; }
        public string Entry11Available { get; set; }
        public string Entry11AdvcPrnt { get; set; }
        public string Entry11Details { get; set; }
        public string Entry11Entity { get; set; }
        public string Entry11Division { get; set; }
        public string Entry11InterAmt { get; set; }
        public string Entry11InterRate { get; set; }
        public string Entry12Type { get; set; }
        public string Entry12IbfCode { get; set; }
        public string Entry12Ccy { get; set; }
        public string Entry12Amt { get; set; }
        public string Entry12Cust { get; set; }
        public string Entry12Actcde { get; set; }
        public string Entry12ActType { get; set; }
        public string Entry12ActNo { get; set; }
        public string Entry12ExchRate { get; set; }
        public string Entry12ExchCcy { get; set; }
        public string Entry12Fund { get; set; }
        public string Entry12CheckNo { get; set; }
        public string Entry12Available { get; set; }
        public string Entry12AdvcPrnt { get; set; }
        public string Entry12Details { get; set; }
        public string Entry12Entity { get; set; }
        public string Entry12Division { get; set; }
        public string Entry12InterAmt { get; set; }
        public string Entry12InterRate { get; set; }
        public string Entry21Type { get; set; }
        public string Entry21IbfCode { get; set; }
        public string Entry21Ccy { get; set; }
        public string Entry21Amt { get; set; }
        public string Entry21Cust { get; set; }
        public string Entry21Actcde { get; set; }
        public string Entry21ActType { get; set; }
        public string Entry21ActNo { get; set; }
        public string Entry21ExchRate { get; set; }
        public string Entry21ExchCcy { get; set; }
        public string Entry21Fund { get; set; }
        public string Entry21CheckNo { get; set; }
        public string Entry21Available { get; set; }
        public string Entry21AdvcPrnt { get; set; }
        public string Entry21Details { get; set; }
        public string Entry21Entity { get; set; }
        public string Entry21Division { get; set; }
        public string Entry21InterAmt { get; set; }
        public string Entry21InterRate { get; set; }
        public string Entry22Type { get; set; }
        public string Entry22IbfCode { get; set; }
        public string Entry22Ccy { get; set; }
        public string Entry22Amt { get; set; }
        public string Entry22Cust { get; set; }
        public string Entry22Actcde { get; set; }
        public string Entry22ActType { get; set; }
        public string Entry22ActNo { get; set; }
        public string Entry22ExchRate { get; set; }
        public string Entry22ExchCcy { get; set; }
        public string Entry22Fund { get; set; }
        public string Entry22CheckNo { get; set; }
        public string Entry22Available { get; set; }
        public string Entry22AdvcPrnt { get; set; }
        public string Entry22Details { get; set; }
        public string Entry22Entity { get; set; }
        public string Entry22Division { get; set; }
        public string Entry22InterAmt { get; set; }
        public string Entry22InterRate { get; set; }
        public string Entry31Type { get; set; }
        public string Entry31IbfCode { get; set; }
        public string Entry31Ccy { get; set; }
        public string Entry31Amt { get; set; }
        public string Entry31Cust { get; set; }
        public string Entry31Actcde { get; set; }
        public string Entry31ActType { get; set; }
        public string Entry31ActNo { get; set; }
        public string Entry31ExchRate { get; set; }
        public string Entry31ExchCcy { get; set; }
        public string Entry31Fund { get; set; }
        public string Entry31CheckNo { get; set; }
        public string Entry31Available { get; set; }
        public string Entry31AdvcPrnt { get; set; }
        public string Entry31Details { get; set; }
        public string Entry31Entity { get; set; }
        public string Entry31Division { get; set; }
        public string Entry31InterAmt { get; set; }
        public string Entry31InterRate { get; set; }
        public string Entry32Type { get; set; }
        public string Entry32IbfCode { get; set; }
        public string Entry32Ccy { get; set; }
        public string Entry32Amt { get; set; }
        public string Entry32Cust { get; set; }
        public string Entry32Actcde { get; set; }
        public string Entry32ActType { get; set; }
        public string Entry32ActNo { get; set; }
        public string Entry32ExchRate { get; set; }
        public string Entry32ExchCcy { get; set; }
        public string Entry32Fund { get; set; }
        public string Entry32CheckNo { get; set; }
        public string Entry32Available { get; set; }
        public string Entry32AdvcPrnt { get; set; }
        public string Entry32Details { get; set; }
        public string Entry32Entity { get; set; }
        public string Entry32Division { get; set; }
        public string Entry32InterAmt { get; set; }
        public string Entry32InterRate { get; set; }
        public string Entry41Type { get; set; }
        public string Entry41IbfCode { get; set; }
        public string Entry41Ccy { get; set; }
        public string Entry41Amt { get; set; }
        public string Entry41Cust { get; set; }
        public string Entry41Actcde { get; set; }
        public string Entry41ActType { get; set; }
        public string Entry41ActNo { get; set; }
        public string Entry41ExchRate { get; set; }
        public string Entry41ExchCcy { get; set; }
        public string Entry41Fund { get; set; }
        public string Entry41CheckNo { get; set; }
        public string Entry41Available { get; set; }
        public string Entry41AdvcPrnt { get; set; }
        public string Entry41Details { get; set; }
        public string Entry41Entity { get; set; }
        public string Entry41Division { get; set; }
        public string Entry41InterAmt { get; set; }
        public string Entry41InterRate { get; set; }
        public string Entry42Type { get; set; }
        public string Entry42IbfCode { get; set; }
        public string Entry42Ccy { get; set; }
        public string Entry42Amt { get; set; }
        public string Entry42Cust { get; set; }
        public string Entry42Actcde { get; set; }
        public string Entry42ActType { get; set; }
        public string Entry42ActNo { get; set; }
        public string Entry42ExchRate { get; set; }
        public string Entry42ExchCcy { get; set; }
        public string Entry42Fund { get; set; }
        public string Entry42CheckNo { get; set; }
        public string Entry42Available { get; set; }
        public string Entry42AdvcPrnt { get; set; }
        public string Entry42Details { get; set; }
        public string Entry42Entity { get; set; }
        public string Entry42Division { get; set; }
        public string Entry42InterAmt { get; set; }
        public string Entry42InterRate { get; set; }
        public string MakerEmpno { get; set; }
        public string Empno { get; set; }
        public DateTime Datestamp { get; set; }
        public string Transno { get; set; }
        public string Xmlmsg { get; set; }
        public string Recstatus { get; set; }
        public DateTime? Timesent { get; set; }
        public DateTime? Timerespond { get; set; }
    }
}
